export const BLOG_SLUGS = [
  "what-champion-should-i-play",
  "lol-random-challenge",
  "fun-lol-challenges",
  "best-champions-for-top-lane",
  "mid-lane-champions-guide",
  "adc-champions-guide",
  "best-support-champions",
  "how-to-improve-at-league",
  "aram-champion-pool",
  "champions-that-counter",
  "what-is-my-main",
  "fun-lol-challenges-with-friends",
  "how-to-climb-ranked",
  "lol-tier-list-current-patch",
  "best-champions-for-beginners",
  "how-to-farm-in-league",
  "understanding-lane-matchups",
  "champion-rotation-guide",
]

export const blogKeywords: Record<string, string[]> = {
  "what-champion-should-i-play": ["what champion should i play lol","league of legends random champion generator","lol random champion generator","random champion picker lol","what champion should i main in league"],
  "lol-random-challenge": ["lol random challenge ideas","league of legends random challenge","lol roulette challenge","random champion challenge league","fun lol challenges with friends"],
  "fun-lol-challenges": ["fun ways to play league of legends","fun lol challenges","league of legends challenge ideas","random champion generator lol fun","lol games to play with friends"],
  "best-champions-for-top-lane": ["best top lane champions","top lane champions current patch","top lane carry champions","how to climb ranked top lane"],
  "mid-lane-champions-guide": ["mid lane champions","best mid lane champions","control mage guide"],
  "adc-champions-guide": ["best ADC champions","ADC carry guide","hyper carry champions"],
  "best-support-champions": ["best support champions","current patch support","engage support guide"],
  "how-to-improve-at-league": ["how to improve at league of legends","loL improvement tips","climb ranked ladder"],
  "aram-champion-pool": ["ARAM champion pool","best ARAM champions"],
  "champions-that-counter": ["champions that counter","lane counters league of legends"],
  "what-is-my-main": ["what is my main league of legends","lol quiz main role"],
  "fun-lol-challenges-with-friends": ["fun lol challenges with friends","lol challenges with friends"],
  "how-to-climb-ranked": ["how to climb ranked league","ranked climb guide"],
  "lol-tier-list-current-patch": ["lol tier list current patch","champion tier list"],
  "best-champions-for-beginners": ["best champions for beginners","easy league champions"],
  "how-to-farm-in-league": ["how to farm in league of legends","last hitting guide"],
  "understanding-lane-matchups": ["lane matchups league of legends","champion matchups"],
  "champion-rotation-guide": ["champion rotation guide","free champions this week"],
}
