// lib/champion-lanes.ts

export const CHAMPION_LANES: Record<string, string[]> = {
  // TOP
  "Aatrox": ["top"],
  
  "Ambessa": ["top"],
  
  "Camille": ["top"],
  "Cho'Gath": ["top", "jungle"],
  "Darius": ["top"],
  "Dr. Mundo": ["top", "jungle"],
  "Fiora": ["top"],
  "Gangplank": ["top"],
  "Garen": ["top"],
  "Gnar": ["top"],
  "Gragas": ["top", "jungle"],
  "Gwen": ["top"],
  "Illaoi": ["top"],
  "Irelia": ["mid", "top"],
  "Jax": ["top"],
  "Jayce": ["top"],
  "K'Sante": ["top"],
  "Kayle": ["top"],
  "Kennen": ["top"],
  "Kled": ["top"],
  "Malphite": ["top"],
  "Maokai": ["top", "support", "jungle"],
  "Mordekaiser": ["top"],
  "Nasus": ["top"],
  "Olaf": ["top", "jungle"],
  "Ornn": ["top"],
  "Pantheon": ["top", "mid", "support"],
  "Poppy": ["top", "jungle", "support"],
  "Quinn": ["top"],
  "Renekton": ["top"],
  "Riven": ["top"],
  "Rumble": ["top"],
  "Sett": ["top"],
  "Shen": ["top", "support"],
  "Singed": ["top"],
  "Sion": ["top"],
  "Tahm Kench": ["support", "top"],
  "Teemo": ["top"],
  "Trundle": ["top", "jungle"],
  "Tryndamere": ["top"],
  "Urgot": ["top"],
  "Vladimir": ["top", "mid"],
  "Volibear": ["top", "jungle"],
  "Wukong": ["top", "jungle"],
  "Yasuo": ["mid", "top"],
  "Yone": ["mid", "top"],
  "Yorick": ["top"],
  "Zaahen": ["top"],
  
  // JUNGLE
  "Amumu": ["jungle"],
  "Bel'Veth": ["jungle"],
  "Brand": ["support", "mid"],
  "Briar": ["jungle"],
  "Diana": ["mid", "jungle"],
  "Ekko": ["jungle", "mid"],
  "Elise": ["jungle"],
  "Evelynn": ["jungle"],
  "Fiddlesticks": ["jungle"],
  "Graves": ["jungle"],
  "Hecarim": ["jungle"],
  "Ivern": ["jungle"],
  "Jarvan IV": ["jungle"],
  "Karthus": ["jungle", "mid"],
  "Kayn": ["jungle"],
  "Kha'Zix": ["jungle"],
  "Kindred": ["jungle"],
  "Lee Sin": ["jungle"],
  "Lillia": ["jungle"],
  "Master Yi": ["jungle"],
  "Nidalee": ["jungle"],
  "Nocturne": ["jungle"],
  "Nunu & Willump": ["jungle"],
  "Rammus": ["jungle"],
  "Rek'Sai": ["jungle"],
  "Rengar": ["jungle", "top"],
  "Sejuani": ["jungle"],
  "Shaco": ["jungle"],
  "Shyvana": ["jungle"],
  "Skarner": ["jungle"],
  "Taliyah": ["jungle", "mid"],
  "Udyr": ["jungle"],
  "Vi": ["jungle"],
  "Viego": ["jungle"],
  "Warwick": ["jungle"],
  "Xin Zhao": ["jungle"],
  "Zac": ["jungle"],
  
  // MID
  "Ahri": ["mid"],
  "Akali": ["mid", "top"],
  "Akshan": ["mid"],
  "Anivia": ["mid"],
  "Annie": ["mid", "support"],
  "Aurelion Sol": ["mid"],
  "Aurora": ["mid"],
  "Azir": ["mid"],
  "Cassiopeia": ["mid"],
  "Corki": ["mid", "adc"],
  "Fizz": ["mid"],
  "Galio": ["mid", "support"],
  "Heimerdinger": ["mid"],
  "Hwei": ["mid", "support"],
  "Kassadin": ["mid"],
  "Katarina": ["mid"],
  "LeBlanc": ["mid"],
  "Lissandra": ["mid"],
  "Lux": ["mid", "support"],
  "Malzahar": ["mid"],
  "Naafiri": ["mid"],
  "Neeko": ["mid", "support"],
  "Orianna": ["mid"],
  "Qiyana": ["mid", "jungle"],
  "Ryze": ["mid"],
  "Sylas": ["mid", "jungle"],
  "Syndra": ["mid"],
  "Talon": ["mid", "jungle"],
  "Twisted Fate": ["mid"],
  "Veigar": ["mid"],
  "Vel'Koz": ["mid", "support"],
  "Vex": ["mid"],
  "Viktor": ["mid"],
  "Xerath": ["mid", "support"],
  "Zed": ["mid"],
  "Ziggs": ["mid", "adc"],
  "Zoe": ["mid"],
  
  // ADC (Marksman)
  "Aphelios": ["adc"],
  "Ashe": ["adc", "support"],
  "Caitlyn": ["adc"],
  "Draven": ["adc"],
  "Ezreal": ["adc"],
  "Jhin": ["adc"],
  "Jinx": ["adc"],
  "Kai'Sa": ["adc"],
  "Kalista": ["adc"],
  "Kog'Maw": ["adc"],
  "Lucian": ["adc", "mid"],
  "Miss Fortune": ["adc"],
  "Nilah": ["adc"],
  "Samira": ["adc"],
  "Senna": ["support", "adc"],
  "Sivir": ["adc"],
  "Smolder": ["adc"],
  "Tristana": ["adc"],
  "Twitch": ["adc"],
  "Varus": ["adc"],
  "Vayne": ["adc"],
  "Yunara": ["adc"],
  "Xayah": ["adc"],
  "Zeri": ["adc"],
  
  // SUPPORT
  "Alistar": ["support"],
  "Bard": ["support"],
  "Blitzcrank": ["support"],
  "Braum": ["support"],
  "Janna": ["support"],
  "Karma": ["support", "mid"],
  "Leona": ["support"],
  "Lulu": ["support"],
  "Mel": ["support", "mid"],
  "Milio": ["support"],
  "Morgana": ["support"],
  "Nami": ["support"],
  "Nautilus": ["support"],
  "Pyke": ["support"],
  "Rakan": ["support"],
  "Rell": ["support"],
  "Renata Glasc": ["support"],
  "Seraphine": ["support", "mid"],
  "Sona": ["support"],
  "Soraka": ["support"],
  "Swain": ["support", "mid"],
  "Taric": ["support"],
  "Thresh": ["support"],
  "Yuumi": ["support"],
  "Zilean": ["support", "mid"],
  "Zyra": ["support"],
}

export function getChampionsByLane(lane: string): string[] {
  if (lane === 'all') return Object.keys(CHAMPION_LANES)
  
  return Object.entries(CHAMPION_LANES)
    .filter(([_, lanes]) => lanes.includes(lane))
    .map(([champion]) => champion)
}

// Helper para normalizar nombres de campeones (Data Dragon IDs vs display names)
export function normalizeChampionName(name: string): string {
  const mapping: Record<string, string> = {
    "Bel'Veth": "Belveth",
    "Cho'Gath": "Chogath",
    "Dr. Mundo": "DrMundo",
    "Jarvan IV": "JarvanIV",
    "K'Sante": "KSante",
    "Kha'Zix": "Khazix",
    "Kog'Maw": "KogMaw",
    "LeBlanc": "Leblanc",
    "Lee Sin": "LeeSin",
    "Master Yi": "MasterYi",
    "Miss Fortune": "MissFortune",
    "Nunu & Willump": "Nunu",
    "Rek'Sai": "RekSai",
    "Renata Glasc": "Renata",
    "Tahm Kench": "TahmKench",
    "Twisted Fate": "TwistedFate",
    "Vel'Koz": "Velkoz",
    "Wukong": "MonkeyKing",
    "Xin Zhao": "XinZhao",
    "Aurelion Sol": "AurelionSol",
  }
  
  return mapping[name] || name.replace(/['\s]/g, '')
}